### ISSUE TITLE
Add dark mode to the Android App

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2683]
Moving to a new bug

### Points fixed
- [x] Logo in homepage and in splash is light mode ([image](https://user-images.githubusercontent.com/1689815/85314655-1a840d80-b4ba-11ea-9e2d-ca6519625ec0.png))
- [x] Image in the `Search by` scan
- [x] Splash screen is still white (#2615 )
- [x] Grey on grey in preferences ([image](https://user-images.githubusercontent.com/12072630/85398179-1f49cf80-b555-11ea-9618-b5c1a4d846f6.png)) (#3298)
- [x] Black on black icon in empty search result "teat" ([image](https://user-images.githubusercontent.com/1689815/85314588-05a77a00-b4ba-11ea-947c-12bd36fb31b8.png)) (#3298)
- [x] Non vector image to replace in search by barcode ([image](https://user-images.githubusercontent.com/1689815/85314617-0cce8800-b4ba-11ea-947e-a1341c15d6aa.png)) (#3299)
- [x] additives browsing ([image](https://user-images.githubusercontent.com/1689815/85314678-24a60c00-b4ba-11ea-8cd1-183ea44bed5c.png))
- [x] Icons in the product page are black on black ([image](https://user-images.githubusercontent.com/1689815/85314732-35ef1880-b4ba-11ea-95ea-6de5e7416d47.png)) (#3298)
- [x] The environment tab is white on white ([image](https://user-images.githubusercontent.com/1689815/85394846-7e0c4a80-b54f-11ea-85fc-3c6c0a6ded60.png)) (#3298)
- [x] Nutrient modifiers in edit mode: ([image](https://user-images.githubusercontent.com/1689815/85446843-3c9e8e00-b595-11ea-9f8d-e131823c7d07.png)) (#3303)
- [x] The environment tab is white on white https://user-images.githubusercontent.com/1689815/85394846-7e0c4a80-b54f-11ea-85fc-3c6c0a6ded60.png
- [x] nutrient modifiers in edit mode: https://user-images.githubusercontent.com/1689815/85446843-3c9e8e00-b595-11ea-9f8d-e131823c7d07.png
- [x] Dark mode vectorial logo for OFF https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/3317

**Comment by sarah541** [comment]
@teolemon  What is the issue? Or the Dark Mode theme is to be implemented completely?

**Comment by teolemon** [comment]
I clarified the wording @sarah541 : this is to implement dark mode
Here's the Open Food Facts logo in dark mode:
https://github.com/openfoodfacts/openfoodfacts-server/blob/3d1a30516a663d1dedad0733fac66d9d93a249c8/html/images/misc/openfoodfacts-logo-no-tagline-dark-mode.svg

**Comment by grravity** [comment]
Big +1 to Dark Mode

**Comment by teolemon** [comment]
This is now in master thanks to @VaiTon

**Comment by teolemon** [comment]
- [ ] Grey on grey in preferences: https://user-images.githubusercontent.com/1689815/85314567-fde7d580-b4b9-11ea-988f-52b1992f54ba.png 
- [ ] Black on black icon in empty search result "teat" https://user-images.githubusercontent.com/1689815/85314588-05a77a00-b4ba-11ea-947c-12bd36fb31b8.png
- [ ] non vector image to replace in search by barcode https://user-images.githubusercontent.com/1689815/85314617-0cce8800-b4ba-11ea-947e-a1341c15d6aa.png
- [ ] logo in homepage is light mode https://user-images.githubusercontent.com/1689815/85314655-1a840d80-b4ba-11ea-9e2d-ca6519625ec0.png
- [ ] additives browsing https://user-images.githubusercontent.com/1689815/85314678-24a60c00-b4ba-11ea-8cd1-183ea44bed5c.png
- [ ] illustrations in the product page are black on black https://user-images.githubusercontent.com/1689815/85314732-35ef1880-b4ba-11ea-95ea-6de5e7416d47.png
- [ ] button not very visible in the ingredient analysis https://user-images.githubusercontent.com/1689815/85314774-41424400-b4ba-11ea-9334-f90c4f708fed.png

**Comment by teolemon** [comment]
- [ ] The environment tab is white on white https://user-images.githubusercontent.com/1689815/85394846-7e0c4a80-b54f-11ea-85fc-3c6c0a6ded60.png

**Comment by teolemon** [comment]
- [ ] nutrient modifiers in edit mode: https://user-images.githubusercontent.com/1689815/85446843-3c9e8e00-b595-11ea-9f8d-e131823c7d07.png

**Comment by teolemon** [comment]
@VaiTon it seems the white tab is fixed

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/85604823-ee02f980-b651-11ea-87b8-c666ae23e001.png)

**Comment by teolemon** [comment]
- [ ] Robotoff modal in Dark mode see also #2931 which is P1 [image](https://user-images.githubusercontent.com/1689815/86404116-4fa91080-bcaf-11ea-9260-718e193e546b.png
)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/86470714-4b770480-bd3c-11ea-9cb1-ac5d0e54636a.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/86470943-b9bbc700-bd3c-11ea-9492-a22d466527d1.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/86471619-0227b480-bd3e-11ea-8b6d-0fd7ca8d6162.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/87205065-cb860700-c306-11ea-88b2-72311ab9279d.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/87205082-d9d42300-c306-11ea-9dbb-af7cc43aa38f.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/87205105-e8223f00-c306-11ea-82ca-bc87209a99c2.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/87205116-f3756a80-c306-11ea-93cc-16dc621cc92a.png)

**Comment by teolemon** [comment]
Thanks @VaiTon closing this bug, and opening a fresh one
