### ISSUE TITLE
Tracker issue for fixes and improvements to the dark mode 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3337]
### Official Android guide to implement dark mode
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

### Fixed
- [x] + sign in the list modal should be white ([image](https://user-images.githubusercontent.com/1689815/87205116-f3756a80-c306-11ea-93cc-16dc621cc92a.png)) (fixed in 45cf75026f72d1512b3eacb752295054a008456b)
- [x] Deharcode color of home text (#3336)
- [x] Background color of cards in compare mode ([image](https://user-images.githubusercontent.com/1689815/87205105-e8223f00-c306-11ea-82ca-bc87209a99c2.png))
- [x] Background color of splash screen should be black ([image](https://user-images.githubusercontent.com/1689815/87205065-cb860700-c306-11ea-88b2-72311ab9279d.png))
- [x] [Fixes in the contributor screen](https://user-images.githubusercontent.com/1689815/87653460-d4873600-c755-11ea-9f06-eee32f3842a0.png)
[Code pointer](https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/main/java/openfoodfacts/github/scrachx/openfood/views/YourListedProductsActivity.java#L272)
- [x] ["Send an updated image" button icon color issue in "Nutrition" tab](https://user-images.githubusercontent.com/1689815/87659602-1caa5680-c75e-11ea-9dd1-4e8d97d68070.png)

### Points that really need fixing
- [x] Add a toggle in the settings for manual override
- [x] [Additives browser text in black](https://user-images.githubusercontent.com/1689815/87653264-9558e500-c755-11ea-9bb2-7ff129a6110d.png)
### Points that can wait

- [ ] Button not very visible in the ingredient analysis ([image](https://user-images.githubusercontent.com/1689815/85314774-41424400-b4ba-11ea-9334-f90c4f708fed.png))
- [ ] Dark mode for Robotoff questions ([image](https://user-images.githubusercontent.com/1689815/86471619-0227b480-bd3e-11ea-8b6d-0fd7ca8d6162.png))
- [ ] Nutrient value modal improvement ([image](https://user-images.githubusercontent.com/1689815/86470943-b9bbc700-bd3c-11ea-9492-a22d466527d1.png))
- [ ] [Request dark mode in webviews](https://developer.android.com/jetpack/androidx/releases/browser#1.2.0-alpha07)
- [ ] Dropdown in the image manager
- [ ] Product page refinements ([image](https://user-images.githubusercontent.com/1689815/86470714-4b770480-bd3c-11ea-9cb1-ac5d0e54636a.png))
- [ ] [Fixes for the allergy screen](https://user-images.githubusercontent.com/1689815/87653159-6fcbdb80-c755-11ea-9de3-05cd89d06992.png)
- [ ] [Background color of cards in the "Contribution" tab (needs to be enabled manually in settings)](https://user-images.githubusercontent.com/1689815/87653900-80c91c80-c756-11ea-92bb-7cabbffa721f.png)
- [ ] [Buttons - Edit mode](https://user-images.githubusercontent.com/1689815/87654109-c1c13100-c756-11ea-8a85-0be5027f5c5b.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/87645830-570bf780-c74e-11ea-9737-0c56ef52c469.png)
- [ ]  a darker black ?
- [ ] a first time modal ?

**Comment by teolemon** [comment]
Fixes for the allergy screen 
![image](https://user-images.githubusercontent.com/1689815/87653159-6fcbdb80-c755-11ea-9de3-05cd89d06992.png)

**Comment by teolemon** [comment]
[Additives browser text in black](https://user-images.githubusercontent.com/1689815/87653264-9558e500-c755-11ea-9bb2-7ff129a6110d.png)

**Comment by teolemon** [comment]
[Fixes in the contributor screen](https://user-images.githubusercontent.com/1689815/87653460-d4873600-c755-11ea-9f06-eee32f3842a0.png)

**Comment by teolemon** [comment]
[Contribution tab (needs to be enabled manually in settings)](https://user-images.githubusercontent.com/1689815/87653900-80c91c80-c756-11ea-92bb-7cabbffa721f.png)

**Comment by teolemon** [comment]
Code for a settings switch: https://gist.githubusercontent.com/KunalChaubal/cefd29ae680def56a0f9d59d590c0955/raw/e2bbd0fe00dd6178684e439f50eef8f0035f7c26/mainActivity.kt

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/89098438-f33d2c00-d3e7-11ea-98d4-0ac3de491dcc.png)
Wondering if the remaining issues with button colors are not related to some extra/missing files

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/89098599-54b1ca80-d3e9-11ea-8468-e41653cad001.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/89098605-672c0400-d3e9-11ea-8b0f-6640b382f881.png)

**Comment by teolemon** [comment]
#3605 adds a Day/Night switch

**Comment by mrudultora** [comment]
Will you please clarify this line _Request dark mode in webviews_. Does that mean that the navigationBar must be according the theme or the whole webpage must adapt according to the dark mode. Some issues mentioned above are already fixed.
I have fixed the remaining ones. Only dark mode in webview is unclear.

**Comment by mrudultora** [comment]
@teolemon Did you mean a dark mode like this? (In the below image Toolbar and navigationBar are in dark mode and brightness reduces by some extent). I don't think there is a way for webpages to be dark.

![img](https://user-images.githubusercontent.com/65870389/107614825-0d967300-6c71-11eb-8ed9-dad8b34da48b.jpeg)
