### ISSUE TITLE
Android 7 tracking issue

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3525]
We fixed a SSL issue that's specific to the Android 7 OS with a workaround that should work for network calls, and was preventing scan, but the rest of the app was having the issues above, and still has the issues above. Are we making network calls with another instance where we have not applied the workaround, is it something else ?

- [x] [Search not working](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3527)
- [x] Taxos seem to be working
- [x] [Images in the history do not work](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/2895) (have underscore?) 
- [x] [Images for ingredient detection do not work](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3524) (it might be some intermediary file,  (https://static.openfoodfacts.org/images/icons/leaf.white.96x96.png)
- [x] [Front image not shown](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3079)

**Comment by teolemon** [comment]
This might be related to underscores in URLs
square/picasso#1570

**Comment by teolemon** [comment]
We fixed a SSL issue that's specific to Android 7, and was preventing scan, but the rest of the app was having the issues above, and still has the issues above.

**Comment by VaiTon** [comment]
This is in need of a retesting. @teolemon?
