### ISSUE TITLE
Open Beauty Facts (Tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4168]
#### Onboarding
- [ ] #4128 

#### Editing

- [ ] #3806
- [ ] #191

#### Product page

- [x] #3805
- [ ] #3263
- [ ] #2056

#### Release 
- [x] #3801 

#### Road to Scores
- [ ] #3326 

#### Papercut bugs

- [x] #3066
- [ ] #3051
- [ ] #2345 (check still the case)

#### Cosmetic sandwich (Road towards a universal app for food and cosmetics)

- [ ] #4195

#### Ingredients
- [ ] #2055 

#### Search

- [x] #1454
- [x] #1456

#### Old issues

```[tasklist]
### Tasks

- [ ] https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/446
- [ ] https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/289
- [ ] https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/288
- [ ] https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/279
- [ ] https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/143
- [ ] https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/157
- [ ] https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/113
- [ ] https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3805
```

### Part of
- #4169
