### ISSUE TITLE
Lists (Tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4208]
#### Shared lists

- [ ] #3872

#### To be sorted

- [ ] [Lists] Useful data for the shopping list lists needs investigation
- [ ] #3373
- [ ] [lists] Add custom products not in the database (shopping list) lists needs investigation
- [ ] #3372
- [ ] Lists: Add the possibility to put the same product several times in a list lists
- [ ] #3078
- [ ] Importing a list makes all product images disappear bug lists
- [ ] #3052
- [ ] Swipe product right to add/move it to a predefined list lists
- [ ] #3050
- [ ] Lists: Allow addition of item by name (new product) feature lists
- [ ] #2929
- [ ] Lists: Allow addition of item by name (autocomplete) feature lists
- [ ] #2928
- [ ] Improve 'shopping list' (products to buy) discoverability feature lists
- [x] #2927
- [ ] Allow to add products from search (or history) in compare mode comparison mockup-required needs investigation
- [ ] #2861
- [ ] Don't allow user to create multiple product lists with same name lists
- [ ] #2512
- [ ] Honor multilingual products in product lists pages
- [ ] #2472
- [ ] Ability to hide specific(s) list(s) of products lists
- [ ] #2280
- [ ] Favorite products & lists (brainstorm) lists Product page ux
- [ ] #694

### Part of
- #4169
